name: arcsoft-web-demo
server:
  port: 8089
  servlet:
    context-path: /
  ssl:
    #证书的路径.
    keyStore: classpath:myarc.keystore
    #证书密码，请修改为您自己证书的密码.
    keyStorePassword: homkey
    #秘钥库类型
    keyStoreType: JKS
    #证书别名
    keyAlias: myarc
#spring
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/arcsoft_web_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      filters: stat,wall,log4j2
      connectionInitSqls: "set names utf8mb4;"
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
  profiles:
    active: dev
